---
networks:
  backend:
    external: true # <-- (Optional) Change this to false if you want to create a new network

volumes:
  postgres-data:
    external: true # <-- (Optional) Change this to false if you want to create a new volume
    
services:
  postgres:
    image: docker.io/library/postgres:16.5
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "${POSTGRES_USER}"']
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    expose:
      - 5432 # <-- Map PostgreSQL port for local access (optional)
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Istanbul                               # <-- Change this to your timezone
      - POSTGRES_USER={{ .ENV.POSTGRESQL_USER }}         # <-- Change this to your username
      - POSTGRES_PASSWORD={{ .ENV.POSTGRESQL_PASSWORD }} # <-- Change this to your password
    networks:
      - backend
