---
networks:
  frontend:
    external: true # <-- (Optional) Change this to false if you want to create a new network
  backend:
    external: true # <-- (Optional) Change this to false if you want to create a new network

volumes:
  freshrss-data:
    external: true # <-- (Optional) Change this to false if you want to create a new volume

services:
  freshrss:
    image: linuxserver/freshrss:1.26.2
    container_name: freshrss
    restart: unless-stopped
    volumes:
      - freshrss-data:/config
    environment:
      - TZ=Europe/Istanbul # <-- Change this to your timezone
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.freshrssM1.compress=true'
      - 'traefik.http.middlewares.freshrssM2.headers.browserXssFilter=true'
      - 'traefik.http.middlewares.freshrssM2.headers.forceSTSHeader=true'
      - 'traefik.http.middlewares.freshrssM2.headers.frameDeny=true'
      - 'traefik.http.middlewares.freshrssM2.headers.referrerPolicy=no-referrer-when-downgrade'
      - 'traefik.http.middlewares.freshrssM2.headers.stsSeconds=31536000'
      - 'traefik.http.routers.freshrss.entryPoints=websecure'
      - 'traefik.http.routers.freshrss.tls.certResolver=cloudflare'
      - 'traefik.http.routers.freshrss.tls=true'
      - 'traefik.http.routers.freshrss.middlewares=freshrssM1,freshrssM2'
      - 'traefik.http.routers.freshrss.rule=Host(`{{ .ENV.DOMAIN }}`)' # <-- Change this to your domain
    networks:
      - frontend
      - backend
    