users:
  username:
    disabled: false
    displayname: 'Your Name'
    password: 'password' # <-- Change this to your password (https://argon2.online/)
    email: 'your-email@proton.me'
    groups:
      - 'admin'
      - 'user'