---
networks:
  frontend:
    external: true # <-- (Optional) Change this to false if you want to create a new network
  backend:
    external: true # <-- (Optional) Change this to false if you want to create a new network

volumes:
  authentik-server-media:
    external: true # <-- (Optional) Change this to false if you want to create a new volume
  authentik-server-templates:
    external: true # <-- (Optional) Change this to false if you want to create a new volume
  authentik-worker-media:
    external: true # <-- (Optional) Change this to false if you want to create a new volume
  authentik-worker-certs:
    external: true # <-- (Optional) Change this to false if you want to create a new volume
  authentik-worker-templates:
    external: true # <-- (Optional) Change this to false if you want to create a new volume

services:
  server:
    image: ghcr.io/goauthentik/server:2024.10.1
    container_name: authentik-server
    command: server
    restart: unless-stopped
    volumes:
      - authentik-server-media:/media
      - authentik-server-templates:/templates
    environment:
      - TZ=Europe/Istanbul                      # <-- Change this to your timezone
      - AUTHENTIK_REDIS__HOST=redis             # <-- Change this to your Redis container name
      - AUTHENTIK_POSTGRESQL__HOST=postgres     # <-- Change this to your PostgreSQL container name
      - AUTHENTIK_POSTGRESQL__USER=username     # <-- Change this to your PostgreSQL username
      - AUTHENTIK_POSTGRESQL__NAME=db_name      # <-- Change this to your PostgreSQL database name
      - AUTHENTIK_POSTGRESQL__PASSWORD=password # <-- Change this to your PostgreSQL password
      - AUTHENTIK_SECRET_KEY=secret             # <-- Change this to your secret key ( run echo $(openssl rand -base64 32) )
    labels:
      - "traefik.enable=true"                                                         # <-- Enable Traefik for this service
      - "traefik.http.routers.authentik-server.rule=Host(`authentik.yourdomain.com`)" # <-- Change this to your domain
      - "traefik.http.routers.authentik-server.entrypoints=websecure"                 # <-- Change this to your entrypoint
      - "traefik.http.routers.authentik-server.tls=true"                              # <-- Do not change this
      - "traefik.http.routers.authentik-server.tls.certresolver=cloudflare"           # <-- Change this to your certresolver
      - "traefik.http.routers.authentik.service=authentik_service"                    # <-- Change this to your service
      - "traefik.http.services.authentik_service.loadbalancer.server.port=9000"       # <-- Change this to your portainer internal port (default: 9000)
    networks:
      - frontend
      - backend

  worker:
    image: ghcr.io/goauthentik/server:2024.10.1
    container_name: authentik-worker
    command: worker
    restart: unless-stopped
    volumes:
      - authentik-worker-media:/media
      - authentik-worker-certs:/certs
      - authentik-worker-templates:/templates
    environment:
      - TZ=Europe/Istanbul                      # <-- Change this to your timezone
      - AUTHENTIK_REDIS__HOST=redis             # <-- Change this to your Redis container name
      - AUTHENTIK_POSTGRESQL__HOST=postgres     # <-- Change this to your PostgreSQL container name
      - AUTHENTIK_POSTGRESQL__USER=username     # <-- Change this to your PostgreSQL username
      - AUTHENTIK_POSTGRESQL__NAME=db_name      # <-- Change this to your PostgreSQL database name
      - AUTHENTIK_POSTGRESQL__PASSWORD=password # <-- Change this to your PostgreSQL password
      - AUTHENTIK_SECRET_KEY=secret             # <-- Change this to your secret key ( run echo $(openssl rand -base64 32) )
    networks:
      - backend
