---
networks:
  frontend:
    external: true
  backend:
    external: true

volumes:
  homepage-data:
    external: true
  homepage-images:
    external: true
  homepage-icons:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.8
    container_name: homepage
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homepage-data:/app/config
      - homepage-images:/app/images
      - homepage-icons:/app/icons
    environment:
      - TZ=Europe/Istanbul
      - LOG_LEVEL=info
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`{{ .ENV.DOMAIN }}`)"
      - "traefik.http.routers.homepage.entryPoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
    networks:
      - frontend
      - backend
    