---
networks:
  backend:
    external: true # <-- (Optional) Change this to false if you want to create a new network

volumes:
  redis-data:
    external: true # <-- (Optional) Change this to false if you want to create a new volume
    
services:
  redis:
    image: docker.io/library/redis:8.2.1
    container_name: redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    expose:
      - 6379 # <-- Map Redis port for local access (optional)
    volumes:
      - redis-data:/data
    environment:
      - TZ=Europe/Istanbul # <-- Change this to your timezone
    networks:
      - backend
