---
networks:
  backend:
    external: true

volumes:
  redis-data:
    external: true
    
services:
  redis:
    image: docker.io/library/redis:7.4.1
    container_name: redis
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis-data:/data
    networks:
      - backend
