networks:
  backend:
    external: true # <-- (Optional) Change this to false if you want to create a new network

volumes:
  mariadb-data:
    external: true # <-- (Optional) Change this to false if you want to create a new volume

services:
  mariadb:
    image: docker.io/library/mariadb:11.6.2
    container_name: mariadb
    restart: unless-stopped
    expose:
      - 3306 # <-- Map MariaDB port for local access (optional)
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - TZ=Europe/Istanbul                             # <-- Change this to your timezone
      - MARIADB_ROOT_PASSWORD={{ .ENV.ROOT_PASSWORD }} # <-- Change this to your MariaDB root password
    networks:
      - backend
