# Define external networks
networks:
  frontend:
    external: true  # Connect to the existing 'frontend' network

# Define external volumes for persistent storage
volumes:
  mariadb-data:
    external: true  # Volume for storing MariaDB data

# Define the MariaDB service
services:
  mariadb:
    image: docker.io/library/mariadb:11.5.2  # MariaDB Docker image version

    container_name: mariadb # Container name
    
    # Expose MariaDB port to local network (optional)
    ports:
      - 3306:3306  # Map MariaDB port for local access

    environment:
      - TZ=Europe/Istanbul
      # Set the root password for MariaDB (remove if you prefer no password)
      - MARIADB_ROOT_PASSWORD=your-root-password
    
    volumes:
      # Mount the volume to persist database data across container restarts
      - mariadb-data:/var/lib/mysql
    
    networks:
      - frontend  # Connect MariaDB to the 'frontend' network

    # Restart the container unless manually stopped
    restart: unless-stopped
