networks:
  backend:
    external: true # <-- (Optional) Change this to false if you want to create a new network

volumes:
  mariadb-data:
    external: true # <-- (Optional) Change this to false if you want to create a new volume

services:
  mariadb:
    image: docker.io/library/mariadb:12.2.2
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306" # <-- Map MariaDB port for local access (optional)
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - backend
  mysqld-exporter:
    image: prom/mysqld-exporter:v0.18.0
    container_name: mysqld-exporter
    ports:
      - "9104:9104" # <-- Map MySQL Exporter port for local access (optional)
    environment:
      DATA_SOURCE_NAME: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mariadb:3306)/
    networks:
      - backend
    depends_on:
      - mariadb
