openai: &openai
  api_key: YOUR_API_KEY

gemini: &gemini
  api_key: YOUR_API_KEY

model_list:
  # OpenAI API
  - model_name: "chatgpt-4o-latest"
    litellm_params:
      <<: *openai
      model: openai/chatgpt-4o-latest

  # Gemini API
  - model_name: "gemini-2.0-flash"
    litellm_params:
      <<: *gemini
      model: gemini/gemini-2.0-flash
      rpm: 15

general_settings:
  master_key: YOUR_MASTER_KEY

cache: true
cache_params:
  type: "redis"
  host: "REDIS_IP"
  port: 6379
  password: "REDIS_PASSWORD"
  namespace: "litellm.caching.caching"
